let questionList = [
                    {
                        id:1, //题目id
                        type:'radio',//单选 checkbox - 多选 ； write - 填空 
                        number:1, //题目序号 - 非必要
                        title:'我国对于艾滋病病毒感染者启动免费抗艾滋病治疗的标准是什么？', //题目名称
                        question_option:[
                            {
                                id:1,//答案id
                                name:'A',//答案选项名
                                content:'出现严重临床表现后',//答案内容
                                active:0//选中状态
                            },
                            {id:2,name:'B',content:'患者想什么时候治疗就什么时候治疗',active:0},
                            {id:3,name:'C',content:'发生高危行为后',active:0},
                            {id:4,name:'D',content:'所有无禁忌症艾滋病病毒感染者均可治疗',active:0},
                            ]//选项集
                    }, 
                    {
                        id:2,
                        type:'radio',
                        number:2,
                        title:'发生无保护性行为具有感染HIV的风险时，可以紧急服用阻断药物越早效果越好。启动阻断药物，从发生危险暴露开始，最长不能超过多少小时？',
                        question_option:[
                            {id:1,name:'A',content:'2小时',active:0},
                            {id:2,name:'B',content:'24小时',active:0},
                            {id:3,name:'C',content:'48小时',active:0},
                            {id:4,name:'D',content:'72小时',active:0},
                            ]
                    },
                    {
                        id:3,
                        type:'radio',
                        number:3,
                        title:'《遏制艾滋病传播实施方案（2019—2022年）》规定流动人口艾滋病防治知识知晓率达（）以上。',
                        question_option:[
                            {id:1,name:'A',content:'75%',active:0},
                            {id:2,name:'B',content:'80%',active:0},
                            {id:3,name:'C',content:'85%',active:0},
                            {id:4,name:'D',content:'90%',active:0},
                            ]
                    },
                    {
                      id:4,
                      type:'radio',
                      number:4,
                      title:'我国公共卫生咨询热线电话是（）。',
                      question_option:[
                        {id:1,name:'A',content:'12315',active:0},
                        {id:2,name:'B',content:'12300',active:0},
                        {id:3,name:'C',content:'12320',active:0},
                        {id:4,name:'D',content:'12520',active:0},
                        ]
                    },
                    {
                      id:5,
                      type:'radio',
                      number:5,
                      title:'世界艾滋病日是每年的何月何日？',
                      question_option:[
                        {id:1,name:'A',content:'6月1日',active:0},
                        {id:2,name:'B',content:'8月1日',active:0},
                        {id:3,name:'C',content:'11月1日',active:0},
                        {id:4,name:'D',content:'12月1日',active:0},
                        ]
                    },
                    {
                      id:6,
                      type:'radio',
                      number:6,
                      title:'抗艾滋病病毒治疗药物需要服用多久？',
                      question_option:[
                        {id:1,name:'A',content:'服药至临床症状消失，后即可停药',active:0},
                        {id:2,name:'B',content:'不能随便停药，通常需要终身服用',active:0},
                        {id:3,name:'C',content:'出现毒副作用，患者可自行停药，之后不能再继续服药',active:0},
                        {id:4,name:'D',content:'都不对',active:0},
                        ]
                    },
                    {
                      id:7,
                      type:'radio',
                      number:7,
                      title:'导致艾滋病的病原体是（）。',
                      question_option:[
                        {id:1,name:'A',content:'HIV',active:0},
                        {id:2,name:'B',content:'HLV',active:0},
                        {id:3,name:'C',content:'HVI',active:0},
                        {id:4,name:'D',content:'IHV',active:0},
                        ]
                    },
                    {
                      id:8,
                      type:'radio',
                      number:8,
                      title:'关于艾滋病疫苗正确的说法是（）。',
                      question_option:[
                        {id:1,name:'A',content:'我国科学家已经研制成功了艾滋病的疫苗',active:0},
                        {id:2,name:'B',content:'目前全世界尚未研制出有效预防艾滋病病毒的疫苗',active:0},
                        {id:3,name:'C',content:'世界上现约有8种艾滋病疫苗',active:0},
                        {id:4,name:'D',content:'都不对',active:0},
                        ]
                    },
                    {
                      id:9,
                      type:'radio',
                      number:9,
                      title:'1981年，哪个国家首先报道世界上第一例艾滋病？',
                      question_option:[
                        {id:1,name:'A',content:'美国',active:0},
                        {id:2,name:'B',content:'泰国',active:0},
                        {id:3,name:'C',content:'中国',active:0},
                        {id:4,name:'D',content:'南非',active:0},
                        ]
                    },
                    {
                      id:10,
                      type:'radio',
                      number:10,
                      title:'3岁儿童确诊感染艾滋病病毒，没有输血史，他最可能的感染途径是（）。',
                      question_option:[
                        {id:1,name:'A',content:'密切接触途径',active:0},
                        {id:2,name:'B',content:'血液途径',active:0},
                        {id:3,name:'C',content:'母婴途径',active:0},
                        {id:4,name:'D',content:'性途径',active:0},
                        ]
                    },
                    {
                      id:11,
                      type:'radio',
                      number:11,
                      title:'下列哪个不是艾滋病的传播途径:',
                      question_option:[
                        {id:1,name:'A',content:'性接触',active:0},
                        {id:2,name:'B',content:'血、血制品、器官移植和污染的注射器',active:0},
                        {id:3,name:'C',content:'蚊虫叮咬',active:0},
                        {id:4,name:'D',content:'母婴垂直传播',active:0},
                        ]
                    },
                    {
                      id:12,
                      type:'radio',
                      number:12,
                      title:'WHO建议具有HIV高危行为的人群至少多久进行一次HIV检测',
                      question_option:[
                        {id:1,name:'A',content:'至少2年1次',active:0},
                        {id:2,name:'B',content:'至少1年1次',active:0},
                        {id:3,name:'C',content:'至少半年1次',active:0},
                        {id:4,name:'D',content:'至少3年1次',active:0},
                        ]
                    },
                    {
                      id:13,
                      type:'radio',
                      number:13,
                      title:'以下哪种情况会感染艾滋病',
                      question_option:[
                        {id:1,name:'A',content:'与艾滋病病毒感染者共用餐饮具，共同进餐',active:0},
                        {id:2,name:'B',content:'与艾滋病病毒感染者一起上班',active:0},
                        {id:3,name:'C',content:'与艾滋病病毒感染者共用注射器',active:0},
                        {id:4,name:'D',content:'与艾滋病病毒感染者一起游泳',active:0},
                        ]
                    },
                    {
                      id:14,
                      type:'radio',
                      number:14,
                      title:'下列哪项是预防经性途径感染艾滋病的有效措施',
                      question_option:[
                        {id:1,name:'A',content:'坚持正确使用安全套',active:0},
                        {id:2,name:'B',content:'拒绝毒品',active:0},
                        {id:3,name:'C',content:'到正规医院拔牙',active:0},
                        {id:4,name:'D',content:'不与人共用牙刷',active:0},
                        ]
                    },
                    {
                      id:15,
                      type:'radio',
                      number:15,
                      title:'《艾滋病防治条例》于何时开始实施',
                      question_option:[
                        {id:1,name:'A',content:'2005.01.01',active:0},
                        {id:2,name:'B',content:'2006.01.01',active:0},
                        {id:3,name:'C',content:'2006.03.01',active:0},
                        {id:4,name:'D',content:'2004.05.01',active:0},
                        ]
                    },
                    {
                      id:16,
                      type:'radio',
                      number:16,
                      title:'艾滋病疫情由()人民政府卫生主管部门统一公布，其他任何单位和个人不得公布',
                      question_option:[
                        {id:1,name:'A',content:'国家级',active:0},
                        {id:2,name:'B',content:'省级',active:0},
                        {id:3,name:'C',content:'市级',active:0},
                        {id:4,name:'D',content:'线、区级',active:0},
                        ]
                    },
                    {
                      id:17,
                      type:'radio',
                      number:17,
                      title:'下列哪种途径传播艾滋病病毒的效率最高',
                      question_option:[
                        {id:1,name:'A',content:'共用注射器吸毒',active:0},
                        {id:2,name:'B',content:'母婴传播',active:0},
                        {id:3,name:'C',content:'输入被污染的血液',active:0},
                        {id:4,name:'D',content:'无保护的性交',active:0},
                        ]
                    },
                    {
                      id:18,
                      type:'radio',
                      number:18,
                      title:'如果你的朋友和邻居感染了艾滋病，你会',
                      question_option:[
                        {id:1,name:'A',content:'保证自己安全的情况下，像往常一样',active:0},
                        {id:2,name:'B',content:'减少去看望',active:0},
                        {id:3,name:'C',content:'告诉朋友不要去他们家',active:0},
                        {id:4,name:'D',content:'钝角',active:0},
                        ]
                    },
                    {
                      id:19,
                      type:'radio',
                      number:19,
                      title:'艾滋病病毒主要侵犯人体的何种细胞()',
                      question_option:[
                        {id:1,name:'A',content:'红细胞',active:0},
                        {id:2,name:'B',content:'白细胞',active:0},
                        {id:3,name:'C',content:'巨噬细胞',active:0},
                        {id:4,name:'D',content:'淋巴细胞',active:0},
                        ]
                    },
										{
										  id:20,
										  type:'radio',
										  number:20,
										  title:'《中华人民共和国传染病防治法》将艾滋病列入哪类传染病',
										  question_option:[
										    {id:1,name:'A',content:'甲类',active:0},
										    {id:2,name:'B',content:'乙类',active:0},
										    {id:3,name:'C',content:'丙类',active:0},
										    {id:4,name:'D',content:'丁类',active:0},
										    ]
										},
                ]
let answer = [
					{id:1,keyFormat:[4]},
					{id:2,keyFormat:[4]},
					{id:3,keyFormat:[4]},
					{id:4,keyFormat:[3]},
					{id:5,keyFormat:[4]},
					{id:6,keyFormat:[2]},
					{id:7,keyFormat:[1]},
					{id:8,keyFormat:[2]},
					{id:9,keyFormat:[1]},
					{id:10,keyFormat:[3]},
					{id:11,keyFormat:[3]},
					{id:12,keyFormat:[3]},
					{id:13,keyFormat:[3]},
					{id:14,keyFormat:[1]},
					{id:15,keyFormat:[3]},
					{id:16,keyFormat:[2]},
					{id:17,keyFormat:[3]},
					{id:18,keyFormat:[1]},
					{id:19,keyFormat:[4]},
					{id:20,keyFormat:[2]},]//正确答案

export{
	questionList,
	answer
}